keycloak:
  enabled: true
  keycloak:
    username: admin
    password: admin
    extraEnv: |
     - name: EXPOSE_URL
       valueFrom:
         configMapKeyRef:
           name: {{ .Release.Name }}-keycloak-http
           key: expose-keycloak-service-key
     - name: HOST_KEY
       valueFrom:
         configMapKeyRef:
           name: {{ .Release.Name }}-keycloak-http
           key: host-key
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.name: activiti1
        fabric8.io/ingress.annotations: |-
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/cors-allow-headers: X-Forwarded-For,X-Forwarded-Proto,X-Forwarded-Port,X-Forwarded-Prefix,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-CSRF-Token,Access-Control-Request-Headers,Access-Control-Request-Method,accept,Keep-Alive
          nginx.ingress.kubernetes.io/enable-cors: true
          nginx.ingress.kubernetes.io/x-forwarded-prefix: true
        fabric8.io/ingress.path: /auth/
    persistence:
      deployPostgres: false
      dbVendor: H2
    ingress:
      enabled: false
      path: /
      hosts:
        - "jx-staging-quickstart-http.jx-staging.35.192.45.39.nip.io"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/configuration-snippet: |
                add_header Access-Control-Allow-Methods "POST, GET, OPTIONS, PUT, PATCH, DELETE";
                add_header Access-Control-Allow-Credentials true;
                add_header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization";
# don't add the allowed origin automatically as then we get twice (because in realm config too?)
#          add_header Access-Control-Allow-Origin $http_origin;
    livenessProbe:
      initialDelaySeconds: 140
    extraVolumes: |
      - name: realm-secret
        secret:
          secretName: {{ .Release.Name }}-realm-secret
    extraVolumeMounts: |
      - name: realm-secret
        mountPath: "/realm/"
        readOnly: true
    extraArgs: -Dkeycloak.import=activiti-realm.json
    preStartScript: |
      /opt/jboss/keycloak/bin/add-user.sh -u admin -p admin
      /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p admin
      cp /realm/activiti-realm.json .
      sed -i "s/activiti-cloud-demo-ui:30082/$HOST_KEY\/ui/g" activiti-realm.json
      sed -i "s/activiti-cloud-demo-ui:\*/$HOST_KEY:*/g" activiti-realm.json
      sed -i "s/placeholder.com/$HOST_KEY:*/g" activiti-realm.json
      sed -i "s/dummy.com/$HOST_KEY:*/g" activiti-realm.json
      sed -i "s/activiti-cloud-sso-idm-kub:30082/$HOST_KEY/g" activiti-realm.json
